### PR TITLE
Remove observationSource from Keepers Job Creation

### PR DESCRIPTION
**Pull request by vla33**

### CODE REVIEW

**Comment by kalverra** [comment]
@vla33 Mind pointing me to the core PR where observation source is dropped from job spec?

**Review by infiloop2 — CHANGES_REQUESTED** [review]
@vla33 a lot of unrelated commits seem to be included in this PR. Can you rebase with just your commit

**Comment by vla33** [comment]
> @vla33 Mind pointing me to the core PR where observation source is dropped from job spec?

Apologies for the super late reply @kalverra! I opened this PR a couple of days ago but forgot to put it in draft mode. The PR where the observation source is removed in the main repo can be found [here](https://github.com/smartcontractkit/chainlink/pull/6582).

**Comment by vla33** [comment]
> @vla33 a lot of unrelated commits seem to be included in this PR. Can you rebase with just your commit

Sorry @infiloop2, I tried to rebase to an older tag yesterday when I was experiencing the issues in the other repo and that's how all these commits appeared. I'll squash them now.

**Pull request closed without merging**
