### PR TITLE
Add lint/tidy for all subprojects in a matrix

### PR DESCRIPTION
**Pull request by tateexon**
- Add lint/tidy checks for subjprojects
- Cleans up docker test envs to be a matrix instead of copy paste
- Not going to set k8s-test-runner lint check as a required check since it needs cleaned up first
- Add gotestloghelper lint to precommit

### CODE REVIEW

**Review by tateexon — COMMENTED** [review]
kick off docker_env tests to test changes to its workflow

**Review by tateexon — COMMENTED** [review]
kick off docker_env tests to test changes to its workflow

**Comment by tateexon** [comment]
kick off docker_env tests to test changes to its workflow

**Comment by tateexon** [comment]
kick off docker_env tests to test changes to its workflow

**Review by kalverra — APPROVED** [review]

**Pull request merged**
